/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsparams = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AmplifyWebApp",
            "endpoint": "https://prg6w8g3y2.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nnOqn87te",
    "aws_user_pools_web_client_id": "42n19u7o9me2f2s05rmrv43pdi",
    "oauth": {},
    "app_linking": {
        "COGNITO_AUTH_URL": 'https://carlos-smart-home-demo.auth.us-east-1.amazoncognito.com/oauth2/authorize',
        "LWA_CLIENT_ID": 'amzn1.application-oa2-client.12d633daffbe43a19b196c05d60914ab',
        "COGNITO_ALEXA_APP_CLIENT_ID": '6rqp05tsalsf0cr4s8ai442hlm',
        "WEB_APP_URL": 'https://master.d2ggj6opg8a13q.amplifyapp.com'
    }
};


export default awsparams;
